name: investive
description: A stock trading information app for FYP


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  provider: ^6.1.1
  fl_chart: ^0.66.2
  charts_flutter: ^0.12.0
  shared_preferences: ^2.2.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  cloud_firestore: ^6.1.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true